---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: infrastructure
resources:
  - namespace.yaml
  - ../base/grafana-loki
  - ../base/kube-prometheus-stack
patchesStrategicMerge:
  - grafana-loki-values.yaml
  - kube-prometheus-stack-values.yaml

